# Generated by Django 4.1.3 on 2023-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='工号')),
                ('password', models.CharField(blank=True, max_length=15, null=True, verbose_name='密码')),
            ],
        ),
    ]
