# Generated by Django 4.1.3 on 2023-02-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_process', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
